AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'Gemfile'
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
