default: &default
  adapter: postgresql
  username: postgres
  password: password
  encoding: unicode
  host: localhost
  pool: 30

development:
  <<: *default
  database: chat_development

test:
  <<: *default
  database: chat_test

development:
  <<: *default
  username: <%= ENV['ACTIVECHAT_DATABASE_USERNAME'] %>
  password: <%= ENV['ACTIVECHAT_DATABASE_PASSWORD'] %>
