local: &local
  url: redis://localhost:6379
  host: localhost
  port: 6379
  timeout: 1
  inline: true

development: *local

test: *local

# production:
#   url: <%= ENV["REDISTOGO_URL"] %>
#   host: soapfish.redistogo.com
#   port: 10110
#   password: 70e4acd671ae805b91c8ff361cc9225a
#   timeout: 1
#   inline: true
