local: &local
  url: redis://localhost:6379
  host: localhost
  port: 6379
  timeout: 1
  inline: true

development: *local

test: *local

production:
  url: <%= ENV["REDISTOGO_URL"] %>
  host: soapfish.redistogo.com
  port: 9263
  password: 251d002f1950efea706a72f877b84ebf
  timeout: 1
  inline: true
